name: Create a Release
on:
  workflow_dispatch:
permissions:
  contents: write # for creating release

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      GH_REPO: ${{ github.repository }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: ./
      with:
        ruby-version: '3.3'
    - run: ruby release.rb
